name: Deploy JS Codestyle
on:
  push:
    paths:
      - js/**
jobs:
  Deploy-JS-Codestyle:
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkoout repository
        uses: actions/checkout@v3
      - name: Set up Node 15
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@kaseya'
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
